import type { Service, Project, Testimonial, ProcessStep, TeamMember, Stat, Feature, TechCategory, PricingPlan, FAQ } from '@/types';

export const SERVICES: Service[] = [
  {
    id: 'web-dev',
    number: '01',
    title: 'Web Development',
    shortDescription: 'Blazing-fast, responsive websites and web applications built with modern frameworks.',
    longDescription: 'We craft production-grade web applications using React, Next.js, and Vue — optimized for performance, SEO, and scalability. From landing pages to complex SaaS platforms, every pixel is intentional. Our engineering team follows best practices for accessibility, progressive enhancement, and server-side rendering to deliver experiences that load in milliseconds.',
    icon: 'Globe',
    features: ['React & Next.js', 'Performance Optimization', 'SEO-First Architecture', 'Progressive Web Apps', 'Server-Side Rendering', 'API Integration'],
    color: 'bg-[#FFF3E8]',
    techStack: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Node.js', 'PostgreSQL'],
    process: [
      { step: '01', title: 'Discovery & Planning', description: 'We map your requirements, user flows, and technical architecture.' },
      { step: '02', title: 'UI/UX Design', description: 'Interactive prototypes tested with real users before development begins.' },
      { step: '03', title: 'Frontend Development', description: 'Component-driven development with modern frameworks and responsive design.' },
      { step: '04', title: 'Backend & API', description: 'RESTful or GraphQL APIs, database design, and server infrastructure.' },
      { step: '05', title: 'Testing & QA', description: 'Automated tests, cross-browser testing, and performance audits.' },
      { step: '06', title: 'Launch & Optimize', description: 'Deployment, monitoring setup, and ongoing performance optimization.' },
    ],
    caseStudies: [
      {
        id: 'cs-vaultify',
        title: 'Vaultify Dashboard',
        client: 'Vaultify Inc.',
        problem: 'Vaultify needed a real-time fintech dashboard capable of handling high-frequency data updates with sub-second latency for portfolio tracking.',
        solution: 'Built a React + TypeScript SPA with WebSocket-driven real-time updates, optimistic UI patterns, and a custom charting engine using D3.js.',
        techUsed: ['React', 'TypeScript', 'D3.js', 'WebSocket', 'Node.js'],
        outcome: '40% faster load times, 99.9% uptime, and a 3x increase in daily active users within 2 months of launch.',
        imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=400&fit=crop',
        category: 'web',
      },
      {
        id: 'cs-nomadstay',
        title: 'NomadStay Marketplace',
        client: 'NomadStay Inc.',
        problem: 'A two-sided marketplace connecting digital nomads with co-living spaces required complex search, booking, and payment workflows.',
        solution: 'Developed a Next.js platform with server-side rendering for SEO, Stripe Connect for split payments, and Mapbox for location-based search.',
        techUsed: ['Next.js', 'Prisma', 'Stripe', 'Mapbox', 'PostgreSQL'],
        outcome: '1,200+ listings in 3 months, 15% conversion rate from search to booking, and featured in TechCrunch.',
        imageUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600&h=400&fit=crop',
        category: 'web',
      },
    ],
  },
  {
    id: 'mobile-dev',
    number: '02',
    title: 'Mobile App Development',
    shortDescription: 'Native and cross-platform mobile apps that users love to open every day.',
    longDescription: 'We build mobile experiences using React Native and Flutter that feel truly native. From ideation to App Store launch, we handle the entire lifecycle with pixel-perfect precision. Our mobile team specializes in offline-first architectures, complex animations, and platform-specific optimizations that keep users engaged.',
    icon: 'Smartphone',
    features: ['React Native & Flutter', 'iOS & Android', 'Push Notifications', 'Offline-First Design', 'App Store Optimization', 'In-App Purchases'],
    color: 'bg-brand-dark',
    techStack: ['React Native', 'Flutter', 'Swift', 'Kotlin', 'Firebase', 'GraphQL'],
    process: [
      { step: '01', title: 'Market Research', description: 'Analyze competitors, user personas, and platform-specific requirements.' },
      { step: '02', title: 'Wireframing & Prototyping', description: 'Interactive prototypes for both iOS and Android with platform-native patterns.' },
      { step: '03', title: 'Cross-Platform Development', description: 'Shared codebase with platform-specific optimizations for performance.' },
      { step: '04', title: 'Native Integration', description: 'Camera, GPS, push notifications, biometrics, and native module bridges.' },
      { step: '05', title: 'App Store Submission', description: 'App Store and Google Play optimization, compliance, and submission.' },
      { step: '06', title: 'Post-Launch Analytics', description: 'Crash reporting, user analytics, and iterative feature development.' },
    ],
    caseStudies: [
      {
        id: 'cs-pulserun',
        title: 'PulseRun Fitness App',
        client: 'PulseRun Health',
        problem: 'PulseRun needed a cross-platform fitness app with real-time GPS tracking, workout planning, and social challenges.',
        solution: 'Built with React Native + MapboxGL for GPS tracking, custom animation system for workout UI, and Firebase for real-time social features.',
        techUsed: ['React Native', 'MapboxGL', 'Firebase', 'Redux'],
        outcome: '100K+ downloads in first quarter, 40% user retention increase, 4.8★ App Store rating.',
        imageUrl: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=600&h=400&fit=crop',
        category: 'mobile',
      },
      {
        id: 'cs-medsync',
        title: 'MedSync Health App',
        client: 'MedSync Health',
        problem: 'A HIPAA-compliant healthcare app for appointment scheduling, medical records, and telemedicine integration.',
        solution: 'Flutter-based app with end-to-end encryption, Twilio for video calls, and secure cloud storage for patient records.',
        techUsed: ['Flutter', 'Dart', 'Firebase', 'Twilio', 'AWS'],
        outcome: 'HIPAA certification achieved, 50K+ patients onboarded, 95% appointment show-up rate.',
        imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&h=400&fit=crop',
        category: 'mobile',
      },
    ],
  },
  {
    id: 'landing-pages',
    number: '03',
    title: 'Landing Page Design',
    shortDescription: 'High-converting landing pages that turn visitors into customers from the first scroll.',
    longDescription: 'We craft landing pages that combine compelling storytelling with conversion-focused design. Every element — from headline hierarchy to CTA placement — is intentional and data-driven. Our pages are built for speed, SEO, and A/B testing readiness, ensuring your marketing spend translates directly into measurable results.',
    icon: 'LayoutTemplate',
    features: ['Conversion Rate Optimization', 'A/B Testing Ready', 'SEO Optimized', 'Lightning Fast Load', 'Analytics Integration', 'Responsive Design'],
    color: 'bg-brand-accent',
    techStack: ['Next.js', 'Tailwind CSS', 'Framer Motion', 'Vercel', 'Google Analytics', 'HubSpot'],
    process: [
      { step: '01', title: 'Goal & Audience Discovery', description: 'Define conversion goals, target personas, traffic sources, and key messaging pillars.' },
      { step: '02', title: 'Copywriting & Content Strategy', description: 'Craft benefit-driven headlines, persuasive body copy, and irresistible CTAs aligned with user intent.' },
      { step: '03', title: 'UX & Visual Design', description: 'Wireframe and design scroll-optimized layouts with trust signals, social proof, and visual hierarchy.' },
      { step: '04', title: 'Development & Animation', description: 'Pixel-perfect implementation with micro-interactions, smooth scroll animations, and modular sections.' },
      { step: '05', title: 'Performance & SEO Audit', description: 'Core Web Vitals optimization, meta tags, schema markup, and sub-2s load time guarantee.' },
      { step: '06', title: 'Analytics & Iteration', description: 'Heatmaps, session recordings, A/B test setup, and data-driven post-launch improvements.' },
    ],
    caseStudies: [
      {
        id: 'cs-launchpad-saas',
        title: 'Launchpad SaaS Landing Page',
        client: 'Launchpad Inc.',
        problem: 'Launchpad had a strong product but a 1.2% trial signup rate due to a cluttered, unfocused landing page that failed to communicate value quickly.',
        solution: 'Redesigned with a single-focus hero, animated product demo, testimonial carousel, and a sticky CTA bar — built in Next.js with Framer Motion animations.',
        techUsed: ['Next.js', 'Framer Motion', 'Tailwind CSS', 'Vercel', 'Hotjar'],
        outcome: 'Trial signup rate jumped from 1.2% to 4.7%, bounce rate dropped 38%, and page load time hit 0.9s on mobile.',
        imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=400&fit=crop',
        category: 'landing-pages',
      },
      {
        id: 'cs-bloom-ecommerce',
        title: 'Bloom Product Launch Page',
        client: 'Bloom Skincare',
        problem: 'Bloom needed a high-impact product launch page for a new skincare line with a tight 3-week deadline and a goal of 10K pre-orders.',
        solution: 'Built a visually rich, editorial-style landing page with countdown timer, influencer video embeds, and Shopify pre-order integration — optimized for Instagram traffic.',
        techUsed: ['Next.js', 'Shopify Storefront API', 'Tailwind CSS', 'Cloudinary', 'Meta Pixel'],
        outcome: '14,200 pre-orders in 72 hours, ROAS of 6.4x on paid campaigns, and featured in Shopify\'s success stories.',
        imageUrl: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&h=400&fit=crop',
        category: 'landing-pages',
      },
    ],
  },
  {
    id: 'custom-software',
    number: '04',
    title: 'Custom Software',
    shortDescription: 'Tailored software solutions that solve your unique business challenges at scale.',
    longDescription: 'When off-the-shelf tools fall short, we engineer bespoke systems. From internal dashboards to enterprise platforms, we architect solutions that grow alongside your organization. Our approach prioritizes clean architecture, comprehensive documentation, and modular design that makes future iterations seamless.',
    icon: 'Cpu',
    features: ['Enterprise Systems', 'API Development', 'Microservices', 'Legacy Modernization', 'Data Pipelines', 'Workflow Automation'],
    color: 'bg-[#E8F4E8]',
    techStack: ['Node.js', 'Python', 'Go', 'PostgreSQL', 'Redis', 'Docker'],
    process: [
      { step: '01', title: 'Requirements Analysis', description: 'Deep-dive into business processes, pain points, and integration needs.' },
      { step: '02', title: 'Architecture Design', description: 'Scalable system architecture with clear boundaries and data flow diagrams.' },
      { step: '03', title: 'Iterative Development', description: 'Agile sprints with weekly demos and stakeholder feedback loops.' },
      { step: '04', title: 'Integration & Migration', description: 'Seamless integration with existing systems and data migration strategies.' },
      { step: '05', title: 'Load Testing', description: 'Performance benchmarking, stress testing, and optimization under real-world conditions.' },
      { step: '06', title: 'Training & Handoff', description: 'Documentation, training sessions, and knowledge transfer to your internal team.' },
    ],
    caseStudies: [
      {
        id: 'cs-greenroute',
        title: 'GreenRoute Logistics Platform',
        client: 'GreenRoute Logistics',
        problem: 'An eco-logistics company needed an AI-powered route optimization engine to reduce carbon emissions for last-mile delivery.',
        solution: 'Custom Python + TensorFlow platform with real-time route optimization, fleet management dashboard, and carbon tracking analytics.',
        techUsed: ['Python', 'TensorFlow', 'Vue.js', 'AWS', 'PostgreSQL'],
        outcome: '35% reduction in delivery costs, 28% lower carbon emissions, processing 10K+ routes daily.',
        imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=400&fit=crop',
        category: 'web',
      },
      {
        id: 'cs-stackboard',
        title: 'Stackboard Project Management',
        client: 'Stackboard Labs',
        problem: 'Needed a collaborative project management SaaS with real-time kanban, time tracking, and team analytics.',
        solution: 'Built with Next.js + WebSocket for real-time collaboration, custom drag-and-drop engine, and Stripe integration for subscriptions.',
        techUsed: ['Next.js', 'PostgreSQL', 'WebSocket', 'Stripe', 'Redis'],
        outcome: 'Launched in 12 weeks, handling 5K concurrent users, $250K ARR within 6 months.',
        imageUrl: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=600&h=400&fit=crop',
        category: 'saas',
      },
    ],
  },
  {
    id: 'ui-ux-design',
    number: '05',
    title: 'UI/UX Design',
    shortDescription: 'Research-driven design that converts visitors into loyal customers and advocates.',
    longDescription: 'Our design process starts with understanding your users. Through research, prototyping, and iterative testing, we create interfaces that are intuitive, accessible, and visually distinctive. We build comprehensive design systems that accelerate development and ensure brand consistency across all touchpoints.',
    icon: 'Palette',
    features: ['User Research', 'Wireframing & Prototyping', 'Design Systems', 'Usability Testing', 'Brand Identity', 'Interaction Design'],
    color: 'bg-[#FAD066]/20',
    techStack: ['Figma', 'Framer', 'Adobe CC', 'Principle', 'Maze', 'Hotjar'],
    process: [
      { step: '01', title: 'User Research', description: 'Interviews, surveys, and competitive analysis to understand user needs.' },
      { step: '02', title: 'Information Architecture', description: 'Sitemaps, user flows, and content strategy for intuitive navigation.' },
      { step: '03', title: 'Wireframing', description: 'Low-fidelity wireframes to validate layout and functionality before visual design.' },
      { step: '04', title: 'Visual Design', description: 'High-fidelity mockups with your brand identity, typography, and color system.' },
      { step: '05', title: 'Prototyping', description: 'Interactive prototypes for stakeholder review and user testing.' },
      { step: '06', title: 'Design System', description: 'Component library, style guide, and design tokens for development handoff.' },
    ],
    caseStudies: [
      {
        id: 'cs-learnforge',
        title: 'LearnForge Design System',
        client: 'LearnForge Education',
        problem: 'An AI-powered e-learning platform needed a cohesive design system to unify their fragmented product experience.',
        solution: 'Created a comprehensive design system with 200+ components, adaptive quizzes UI, and accessibility-first patterns in Figma.',
        techUsed: ['Figma', 'React', 'Storybook', 'Tailwind CSS'],
        outcome: 'Dev team velocity increased 60%, design-to-code time reduced by 40%, WCAG AA compliance achieved.',
        imageUrl: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=600&h=400&fit=crop',
        category: 'saas',
      },
    ],
  },
  {
    id: 'cloud-solutions',
    number: '06',
    title: 'Cloud Solutions',
    shortDescription: 'Scalable, secure cloud infrastructure that keeps your applications running 24/7.',
    longDescription: 'We design and manage cloud environments on AWS, GCP, and Azure. From CI/CD pipelines to auto-scaling architecture, your infrastructure is built for reliability and cost efficiency. Our DevOps engineers ensure zero-downtime deployments and proactive monitoring across your entire stack.',
    icon: 'Cloud',
    features: ['AWS & GCP & Azure', 'CI/CD Pipelines', 'Container Orchestration', 'Cost Optimization', 'Auto-Scaling', 'Disaster Recovery'],
    color: 'bg-[#E8EEF4]',
    techStack: ['AWS', 'GCP', 'Docker', 'Kubernetes', 'Terraform', 'GitHub Actions'],
    process: [
      { step: '01', title: 'Infrastructure Audit', description: 'Review existing setup, identify bottlenecks, and plan migration strategy.' },
      { step: '02', title: 'Architecture Design', description: 'Cloud-native architecture with high availability and auto-scaling.' },
      { step: '03', title: 'Infrastructure as Code', description: 'Terraform/CloudFormation for reproducible, version-controlled infrastructure.' },
      { step: '04', title: 'CI/CD Pipeline', description: 'Automated build, test, and deployment pipelines for rapid iteration.' },
      { step: '05', title: 'Monitoring & Alerts', description: 'Comprehensive observability with dashboards, logging, and alerting.' },
      { step: '06', title: 'Cost Optimization', description: 'Ongoing resource optimization, reserved instances, and spending analysis.' },
    ],
    caseStudies: [
      {
        id: 'cs-cloudhive',
        title: 'Cloudhive Analytics Platform',
        client: 'Cloudhive Analytics',
        problem: 'An analytics SaaS needed to scale from 1K to 100K users while keeping infrastructure costs under control.',
        solution: 'Migrated to Kubernetes on AWS with auto-scaling, implemented caching layers with Redis, and optimized database queries.',
        techUsed: ['AWS', 'Kubernetes', 'Docker', 'Redis', 'Terraform'],
        outcome: '60% infrastructure cost reduction, 99.99% uptime, handles 3x peak traffic without manual intervention.',
        imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=400&fit=crop',
        category: 'saas',
      },
    ],
  },
  {
    id: 'backend-dev',
    number: '07',
    title: 'Backend Development',
    shortDescription: 'Robust, scalable server-side systems and APIs that power your applications reliably.',
    longDescription: 'We engineer backend systems built for scale, security, and speed. From RESTful APIs to event-driven microservices, our backend team creates the invisible foundation that makes great products possible. Every system we build is documented, tested, and designed for maintainability.',
    icon: 'Server',
    features: ['RESTful & GraphQL APIs', 'Microservices Architecture', 'Database Design', 'Message Queues', 'Caching Strategies', 'Real-time Systems'],
    color: 'bg-[#F0E8F4]',
    techStack: ['Node.js', 'Python', 'Go', 'PostgreSQL', 'MongoDB', 'RabbitMQ'],
    process: [
      { step: '01', title: 'API Design', description: 'OpenAPI specs, data models, and endpoint architecture before coding.' },
      { step: '02', title: 'Database Architecture', description: 'Schema design, indexing strategy, and data migration planning.' },
      { step: '03', title: 'Core Development', description: 'Type-safe backend code with comprehensive error handling and logging.' },
      { step: '04', title: 'Integration Layer', description: 'Third-party API integrations, webhooks, and event-driven communication.' },
      { step: '05', title: 'Testing & Security', description: 'Unit tests, integration tests, penetration testing, and security audits.' },
      { step: '06', title: 'Deployment & Monitoring', description: 'Containerized deployment with health checks, logging, and performance monitoring.' },
    ],
    caseStudies: [
      {
        id: 'cs-vaultify-api',
        title: 'Vaultify API Infrastructure',
        client: 'Vaultify Inc.',
        problem: 'Vaultify needed a high-throughput API layer capable of processing 50K financial transactions per minute with zero data loss.',
        solution: 'Built event-driven microservices with Go, message queues for guaranteed delivery, and PostgreSQL with read replicas.',
        techUsed: ['Go', 'PostgreSQL', 'RabbitMQ', 'Redis', 'Docker'],
        outcome: 'Handles 80K transactions/min, zero data loss over 18 months, sub-50ms API response times.',
        imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=400&fit=crop',
        category: 'web',
      },
      {
        id: 'cs-stackboard-api',
        title: 'Stackboard Real-Time Backend',
        client: 'Stackboard Labs',
        problem: 'Real-time collaboration for 5K concurrent users required a backend that could handle persistent connections and complex state sync.',
        solution: 'WebSocket server in Node.js with Redis pub/sub for horizontal scaling, CRDT-based conflict resolution for collaborative editing.',
        techUsed: ['Node.js', 'WebSocket', 'Redis', 'PostgreSQL', 'Docker'],
        outcome: '5K concurrent users with <100ms sync latency, 99.95% uptime, seamless horizontal scaling.',
        imageUrl: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=600&h=400&fit=crop',
        category: 'saas',
      },
    ],
  },
  {
    id: 'security',
    number: '08',
    title: 'Security Enhancement',
    shortDescription: 'Comprehensive security audits and hardening to protect your digital assets.',
    longDescription: 'Security is not an afterthought — it is the foundation. Our security team conducts thorough penetration testing, vulnerability assessments, and compliance audits. We implement defense-in-depth strategies covering authentication, encryption, network security, and incident response planning.',
    icon: 'ShieldCheck',
    features: ['Penetration Testing', 'Security Audits', 'OWASP Compliance', 'Encryption Implementation', 'Access Control', 'Incident Response'],
    color: 'bg-[#FDE8E8]',
    techStack: ['Burp Suite', 'OWASP ZAP', 'Snyk', 'Vault', 'Cloudflare', 'Auth0'],
    process: [
      { step: '01', title: 'Threat Assessment', description: 'Identify attack vectors, vulnerabilities, and risk levels across your stack.' },
      { step: '02', title: 'Penetration Testing', description: 'Simulated attacks to find weaknesses before bad actors do.' },
      { step: '03', title: 'Security Architecture', description: 'Design defense-in-depth layers covering network, application, and data.' },
      { step: '04', title: 'Implementation', description: 'Harden systems with encryption, WAF, rate limiting, and access controls.' },
      { step: '05', title: 'Compliance Audit', description: 'Ensure SOC 2, GDPR, HIPAA, or PCI-DSS compliance as required.' },
      { step: '06', title: 'Monitoring & Response', description: 'Continuous monitoring, alerting, and incident response playbooks.' },
    ],
    caseStudies: [
      {
        id: 'cs-medsync-sec',
        title: 'MedSync HIPAA Compliance',
        client: 'MedSync Health',
        problem: 'A healthcare platform handling sensitive patient data needed full HIPAA compliance and security hardening.',
        solution: 'End-to-end encryption, role-based access control, comprehensive audit logging, and automated vulnerability scanning.',
        techUsed: ['Auth0', 'Vault', 'Cloudflare', 'AWS KMS', 'Snyk'],
        outcome: 'Full HIPAA certification achieved, zero security incidents over 2 years, passed 3 independent audits.',
        imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&h=400&fit=crop',
        category: 'mobile',
      },
    ],
  },
  {
    id: 'domain-hosting',
    number: '09',
    title: 'Domain & Hosting',
    shortDescription: 'Reliable domain management and high-performance hosting solutions for your business.',
    longDescription: 'We provide end-to-end domain registration, DNS management, and enterprise-grade hosting solutions. Our managed hosting ensures your applications stay fast, secure, and available with 99.99% uptime SLAs, automatic SSL, and global CDN distribution.',
    icon: 'Globe2',
    features: ['Domain Registration', 'DNS Management', 'Managed Hosting', 'SSL Certificates', 'CDN Distribution', 'Email Hosting'],
    color: 'bg-[#E8F0E4]',
    techStack: ['Cloudflare', 'AWS', 'Vercel', 'Nginx', 'Let\'s Encrypt', 'Route 53'],
    process: [
      { step: '01', title: 'Domain Strategy', description: 'Domain selection, registration, and brand protection across TLDs.' },
      { step: '02', title: 'DNS Configuration', description: 'Optimized DNS setup with failover, geographic routing, and DNSSEC.' },
      { step: '03', title: 'Hosting Setup', description: 'Server provisioning, SSL installation, and application deployment.' },
      { step: '04', title: 'CDN Integration', description: 'Global content delivery for fastest load times worldwide.' },
      { step: '05', title: 'Email Configuration', description: 'Professional email setup with SPF, DKIM, and DMARC protection.' },
      { step: '06', title: 'Monitoring & Maintenance', description: 'Uptime monitoring, automatic backups, and proactive maintenance.' },
    ],
    caseStudies: [
      {
        id: 'cs-nomadstay-host',
        title: 'NomadStay Global Infrastructure',
        client: 'NomadStay Inc.',
        problem: 'A global marketplace needed hosting that could serve users across 40+ countries with consistent sub-2s page loads.',
        solution: 'Multi-region AWS deployment with Cloudflare CDN, edge caching, and automated failover across 3 availability zones.',
        techUsed: ['AWS', 'Cloudflare', 'Terraform', 'Docker', 'Nginx'],
        outcome: '99.99% uptime, average page load of 1.2s globally, 40% reduction in hosting costs.',
        imageUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600&h=400&fit=crop',
        category: 'web',
      },
    ],
  },
  {
    id: 'testing',
    number: '10',
    title: 'Software Testing',
    shortDescription: 'Rigorous QA and automated testing to ship bug-free, reliable software every time.',
    longDescription: 'Quality is non-negotiable. Our QA engineers combine automated testing frameworks with manual exploratory testing to catch every edge case. We implement test-driven development, continuous integration testing, and comprehensive regression suites that give you confidence in every release.',
    icon: 'Bug',
    features: ['Automated Testing', 'Manual QA', 'Performance Testing', 'Security Testing', 'Mobile Testing', 'CI/CD Integration'],
    color: 'bg-[#FFF8E1]',
    techStack: ['Jest', 'Cypress', 'Playwright', 'k6', 'Selenium', 'Appium'],
    process: [
      { step: '01', title: 'Test Strategy', description: 'Define test scope, coverage targets, and testing approach per feature.' },
      { step: '02', title: 'Test Planning', description: 'Create test cases, test data, and environment requirements.' },
      { step: '03', title: 'Automated Framework', description: 'Set up CI-integrated automated testing with unit, integration, and E2E tests.' },
      { step: '04', title: 'Execution & Reporting', description: 'Run test suites, document findings, and prioritize bug fixes.' },
      { step: '05', title: 'Performance Testing', description: 'Load testing, stress testing, and performance benchmarking under real conditions.' },
      { step: '06', title: 'Regression & Maintenance', description: 'Ongoing regression testing and test suite maintenance for each release.' },
    ],
    caseStudies: [
      {
        id: 'cs-cloudhive-qa',
        title: 'Cloudhive QA Transformation',
        client: 'Cloudhive Analytics',
        problem: 'Release cycles were slow due to manual testing bottlenecks — each release took 2 weeks of QA.',
        solution: 'Implemented a comprehensive automated testing framework with Cypress for E2E, Jest for unit tests, and k6 for load testing.',
        techUsed: ['Cypress', 'Jest', 'k6', 'GitHub Actions', 'Docker'],
        outcome: 'Release cycle reduced from 2 weeks to 2 days, 95% test coverage, zero critical bugs in production for 8 months.',
        imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=400&fit=crop',
        category: 'saas',
      },
    ],
  },
];

export const PROJECTS: Project[] = [
  {
    id: 'proj-1',
    title: 'Vaultify',
    description: 'A fintech dashboard for managing digital assets with real-time portfolio tracking and secure transaction workflows.',
    category: 'web',
    techStack: ['React', 'TypeScript', 'Tailwind', 'Node.js'],
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=400&fit=crop',
    year: '2025',
    client: 'Vaultify Inc.',
  },
  {
    id: 'proj-2',
    title: 'Java Developer Portfolio',
    description: 'A modern developer portfolio showcasing Java and Spring Boot projects, featuring REST APIs, scalable backend architecture, and interactive UI with smooth animations.',
    category: 'landing',
    techStack: ['Java', 'Spring Boot', 'React', 'Tailwind', 'GSAP'],
    imageUrl: '/project/portfolio.png',
    year: '2025',
    link: 'https://java-dev-portfolio.vercel.app/',
    client: 'Personal Project',
  },
  {
    id: 'proj-3',
    title: 'SolarEcoo',
    description: 'SolarEcoo provides smart solar panel installation solutions, enabling users to reduce electricity costs and embrace sustainable, eco-friendly energy.',
    category: 'web',
    techStack: ['React', 'PostgreSQL', 'Tailwind CSS', 'AWS', 'Spring Boot'],
    imageUrl: '/project/solarecoo.png',
    link: 'https://solar-ecoo.vercel.app/',
    year: '2025',
    client: 'Solar Ecoo',
  },
    {
    id: 'proj-4',
    title: 'RankLocal',
    description: 'A location-based platform that helps users compare nearby shops using real user reviews, ratings, and feedback—making it easier to discover and choose the best local services.',
    category: 'fullstack',
    techStack: ['Java', 'Spring Boot', 'React', 'MySQL', 'Google Maps API'],
    imageUrl: '/project/ranklocal.png',
    year: '2025',
    link: 'https://rankview.vercel.app/',
    client: 'Personal Project',
  }, 
  {
    id: 'proj-5',
    title: 'Stackboard',
    description: 'A collaborative project management SaaS with real-time kanban boards, time tracking, and team analytics.',
    category: 'saas',
    techStack: ['Next.js', 'PostgreSQL', 'WebSocket', 'Stripe'],
    imageUrl: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=600&h=400&fit=crop',
    year: '2025',
    client: 'Stackboard Labs',
  },
  {
    id: 'proj-6',
    title: 'GreenRoute',
    description: 'An eco-logistics platform optimizing delivery routes to reduce carbon emissions for last-mile delivery.',
    category: 'web',
    techStack: ['Vue.js', 'Python', 'TensorFlow', 'AWS'],
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=400&fit=crop',
    year: '2024',
    client: 'GreenRoute Logistics',
  },
  {
    id: 'proj-7',
    title: 'Nexora',
    description: 'An AI-powered automation platform that streamlines workflows using intelligent agents that learn, adapt, and execute tasks—helping teams eliminate repetitive work and focus on high-impact outcomes.',
    category: 'saas',
    techStack: ['Java', 'Spring Boot', 'Microservices', 'React', 'Tailwind', 'AI'],
    imageUrl: '/project/nexora.png',
    year: '2025',
    link: 'https://nexora-rouge-mu.vercel.app/',
    client: 'Personal Project',
  },

  {
    id: 'proj-8',
    title: 'MedSync',
    description: 'A healthcare appointment and records management app with telemedicine integration and HIPAA compliance.',
    category: 'mobile',
    techStack: ['Flutter', 'Dart', 'Firebase', 'Twilio'],
    imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&h=400&fit=crop',
    year: '2024',
    client: 'MedSync Health',
  },
  {
    id: 'proj-9',
    title: 'Cloudhive',
    description: 'An analytics SaaS platform providing real-time insights, custom dashboards, and automated reporting.',
    category: 'saas',
    techStack: ['React', 'D3.js', 'Go', 'Kubernetes'],
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=400&fit=crop',
    year: '2024',
    client: 'Cloudhive Analytics',
  },
  {
    id: 'proj-10',
    title: 'NomadStay',
    description: 'A digital nomad accommodation marketplace connecting remote workers with unique co-living spaces.',
    category: 'web',
    techStack: ['Next.js', 'Prisma', 'Stripe', 'Mapbox'],
    imageUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600&h=400&fit=crop',
    year: '2025',
    client: 'NomadStay Inc.',
  },
  {
    id: 'proj-11',
    title: 'Designer Portfolio',
    description: 'A visually rich portfolio showcasing UI/UX design projects, interactive prototypes, and modern layouts with smooth animations and responsive design.',
    category: 'landing',
    techStack: ['Figma', 'React', 'Tailwind', 'Framer Motion', 'GSAP'],
    imageUrl: '/project/designer-portfolio.png',
    year: '2025',
    link: 'https://portfolio-landing-zqhv.vercel.app/',
    client: 'Personal Project',
  },

  {
    id: 'proj-12',
    title: 'LearnForge',
    description: 'An AI-powered e-learning platform with adaptive quizzes, progress tracking, and collaborative study rooms.',
    category: 'saas',
    techStack: ['React', 'Python', 'OpenAI', 'Redis'],
    imageUrl: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=600&h=400&fit=crop',
    year: '2025',
    client: 'LearnForge Education',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 'test-1',
    name: 'Priya',
    role: 'CTO',
    company: 'Vaultify Inc.',
    feedback: 'FlatOrbit ne aamchya fintech dashboard cha sapna pratyakshaat aanlaa. Technical kaam ekdum solid hote ani deadline aadhi complete kelee. Aamhi khup satisfied aahe.',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=80&h=80&fit=crop&crop=face',
    rating: 5,
  },
  {
    id: 'test-2',
    name: 'Omkar',
    role: 'Founder',
    company: 'PulseRun Health',
    feedback: 'Aamchi mobile app ekdum native feel dete. Pehilya mahinyaat user retention 40% vadhle. FlatOrbit chi team saglyat best aahe, khare sangto!',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&crop=face',
    rating: 5,
  },
  {
    id: 'test-3',
    name: 'Vaishali',
    role: 'VP of Product',
    company: 'Stackboard Labs',
    feedback: '12 aathvadyaat aamcha poorna SaaS platform ready keela. Hazaro concurrent users handle karto ani kutheyahi problem nahi. FlatOrbit che kaam apratim aahe!',
    avatarUrl: 'https://images.unsplash.com/photo-1598550874175-4d0ef436c909?w=80&h=80&fit=crop&crop=face',
    rating: 5,
  },
  {
    id: 'test-4',
    name: 'Rohan',
    role: 'CEO',
    company: 'GreenRoute Logistics',
    feedback: 'Aamcha infrastructure kharch 60% kami jhala ani traffic teen patine vadhle. FlatOrbit ne sustainable engineering chi kadar khara arthaane dakhayli.',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=80&h=80&fit=crop&crop=face',
    rating: 5,
  },
  {
    id: 'test-5',
    name: 'Snehal',
    role: 'Head of Design',
    company: 'LearnForge Education',
    feedback: 'FlatOrbit ne aaplyasaathi banvlela design system khupach sundar aahe. Consistent, accessible ani ekdum professional. Aamchya team cha vel mahine waachla.',
    avatarUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=80&h=80&fit=crop&crop=face',
    rating: 5,
  },
  {
    id: 'test-6',
    name: 'Sagar',
    role: 'CTO',
    company: 'MedSync Health',
    feedback: 'HIPAA-compliant, design mast aahe, ani schedule aadhi deliver kelee. Health-tech startup la FlatOrbit saarkhaa partner milaawa yaacha naseeb laagato!',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=80&h=80&fit=crop&crop=face',
    rating: 5,
  },
  {
    id: 'test-7',
    name: 'Ananya Sharma',
    role: 'CTO',
    company: 'Vaultify Inc.',
    feedback: 'FlatOrbit turned our fintech vision into a production-ready dashboard that honestly blew us away. Their team understood our requirements from day one and delivered without a single back-and-forth delay.',
    avatarUrl: 'https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=80&h=80&fit=crop&crop=face',
    rating: 5,
  },
  {
    id: 'test-8',
    name: 'Arjun Mehta',
    role: 'Founder',
    company: 'PulseRun Health',
    feedback: 'The app FlatOrbit built for us feels incredibly polished. Our users kept saying it feels better than apps from much bigger companies. Retention jumped 40% in the first month — numbers don\'t lie.',
    avatarUrl: 'https://images.unsplash.com/photo-1618641986557-1ecd230959aa?w=80&h=80&fit=crop&crop=face',
    rating: 5,
  },
  {
    id: 'test-9',
    name: 'Kavya Nair',
    role: 'VP of Product',
    company: 'Stackboard Labs',
    feedback: 'From kickoff call to go-live in 12 weeks — FlatOrbit shipped a full SaaS platform that handles thousands of concurrent users without flinching. I have worked with many agencies, these people are different.',
    avatarUrl: 'https://images.unsplash.com/photo-1614644147798-f8c0fc9da7f6?w=80&h=80&fit=crop&crop=face',
    rating: 5,
  },
  {
    id: 'test-10',
    name: 'Rahul Desai',
    role: 'CEO',
    company: 'GreenRoute Logistics',
    feedback: 'Our AWS bills dropped by 60% after FlatOrbit rearchitected our infrastructure, and we are now handling 3x the traffic. That combination is almost unheard of. Genuinely one of the best decisions we made.',
    avatarUrl: 'https://images.unsplash.com/photo-1566753323558-f4e0952af115?w=80&h=80&fit=crop&crop=face',
    rating: 5,
  },
  {
    id: 'test-11',
    name: 'Pooja Iyer',
    role: 'Head of Design',
    company: 'LearnForge Education',
    feedback: 'The design system FlatOrbit created is something our in-house team now builds on top of every single day. Accessible, consistent, and genuinely beautiful. It saved us months of foundational work.',
    avatarUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=80&h=80&fit=crop&crop=face',
    rating: 5,
  },
  {
    id: 'test-12',
    name: 'Vikram Joshi',
    role: 'CTO',
    company: 'MedSync Health',
    feedback: 'HIPAA compliance, clean UI, delivered ahead of schedule — FlatOrbit checked every box we had and a few we hadn\'t even thought of. Every health-tech startup needs an engineering partner like this.',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&crop=face',
    rating: 5,
  },
];

export const PROCESS_STEPS: ProcessStep[] = [
  {
    number: '01',
    title: 'Your Idea Takes Shape',
    description: 'We listen, research, and map your vision into a clear strategy with defined milestones.',
    icon: 'Lightbulb',
  },
  {
    number: '02',
    title: 'Beautiful & Functional UI/UX',
    description: 'Interactive prototypes and user-tested designs before writing a single line of code.',
    icon: 'Palette',
  },
  {
    number: '03',
    title: 'Code Meets Craft',
    description: 'Agile sprints, weekly demos, and production-grade engineering from day one.',
    icon: 'Code',
  },
  {
    number: '04',
    title: 'Quality Assurance',
    description: 'Automated and manual testing across devices, browsers, and edge cases.',
    icon: 'Shield',
  },
  {
    number: '05',
    title: 'Go Live With Confidence',
    description: 'Seamless deployment, monitoring setup, and performance optimization at launch.',
    icon: 'Rocket',
  },
  {
    number: '06',
    title: 'Scale & Iterate',
    description: 'Post-launch support, analytics-driven improvements, and growth-ready architecture.',
    icon: 'TrendingUp',
  },
];

export const FEATURES: Feature[] = [
  {
    id: 'feat-1',
    title: 'Long-Term Tech Partnership',
    description: 'We stay with you post-launch. Ongoing support, iterations, and scaling as your business grows.',
    icon: 'Handshake',
  },
  {
    id: 'feat-3',
    title: 'Fast Delivery',
    description: 'Ship in weeks, not months. Lean processes and battle-tested boilerplates accelerate delivery.',
    icon: 'Zap',
  },
  {
    id: 'feat-5',
    title: 'Growth-Oriented Thinking',
    description: 'Architecture built for scale. We think about your next million users from day one.',
    icon: 'BarChart3',
  },

  {
    id: 'feat-7',
    title: 'WhatsApp-Friendly Communication',
    description: 'No complex project tools or email chains. We keep you updated directly on WhatsApp in a language you are comfortable with.',
    icon: 'Whatsapp',
  },
  {
    id: 'feat-8',
    title: 'Transparent, Fixed Pricing',
    description:
      'No hidden charges. You get a detailed quote in writing before we begin — with GST invoice provided.',
    icon: 'IndianRupee',
  },
  {
    id: 'feat-9',
    title: 'Full Code Ownership',
    description:
      'Your code, your domain, your data. Everything is handed over at project end — no lock-ins, ever.',
    icon: 'ShieldCheck',
  },
];

export const TECH_STACK: TechCategory[] = [
  {
    title: 'Frontend',
    items: [
      { name: 'React', icon: 'Code' },
      { name: 'Next.js', icon: 'Globe' },
      { name: 'TypeScript', icon: 'FileCode' },
      { name: 'Tailwind', icon: 'Paintbrush' },
      { name: 'Vue.js', icon: 'Layers' },
    ],
  },
  {
    title: 'Backend',
    items: [
      { name: 'Java', icon: 'Server' },
      { name: 'Spring Boot', icon: 'Terminal' },
      { name: 'Spring', icon: 'Cpu' },
      { name: 'RESTful', icon: 'Share2' },
      { name: 'PostgreSQL', icon: 'Database' },
    ],
  },
  {
    title: 'Mobile',
    items: [
      { name: 'React Native', icon: 'Smartphone' },
      { name: 'Flutter', icon: 'Feather' },
      { name: 'Swift', icon: 'Blocks' },
      { name: 'Kotlin', icon: 'Blocks' },
    ],
  },
  {
    title: 'Cloud & DevOps',
    items: [
      { name: 'AWS', icon: 'Cloud' },
      { name: 'Docker', icon: 'Box' },
      { name: 'Kubernetes', icon: 'Network' },
      { name: 'Vercel', icon: 'Triangle' },
      { name: 'GitHub Actions', icon: 'GitBranch' },
    ],
  },
];

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'tm-1',
    name: 'Ranjit Dabade',
    role: 'CEO',
    avatarUrl: '/about/ranjit.png',
    bio: '15 years shipping digital products. Previously engineering lead at Stripe.',
  },
  {
    id: 'tm-2',
    name: 'Vinayak Jadhav',
    role: 'CTO',
    avatarUrl: '/about/vinayak.png',
    bio: 'Full-stack architect with a passion for performant, accessible code.',
  },

];

export const STATS: Stat[] = [
  { label: 'Projects Delivered', value: '20', suffix: '+' },
  { label: 'Happy Clients', value: '95', suffix: '%' },
  { label: 'Team Members', value: '5', suffix: '' },
  { label: 'Years in Business', value: '1', suffix: '+' },
];

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: 'launch',
    name: 'Launch',
    price: { monthly: 10999, yearly: 9999 },
    description: 'For startups and businesses launching a focused digital product or MVP.',
    features: [
      'Single project (website, MVP, or internal tool)',
      'Discovery & scoping session included',
      'UI/UX design included',
      'Mobile-responsive build',
      'Basic SEO & analytics setup',
      '2 revision rounds',
      '30-day post-launch support',
      'Full source code & asset handoff',
    ],
    highlighted: false,
    cta: 'Get a Quote',
    // priceNote: 'starts at · exact quote after scoping call',
  },
  {
    id: 'build',
    name: 'Build',
    price: { monthly: 48999, yearly: 45999 },
    description: 'For growing companies with larger or multi-phase product needs.',
    features: [
      'Multi-phase or complex project scope',
      'Full product design system',
      'Web + mobile (cross-platform)',
      'Advanced SEO & analytics integration',
      'API & third-party integrations',
      'CI/CD pipeline setup',
      'Priority bug fixes & performance monitoring',
      '90-day post-launch support',
      'Full source code & asset handoff',
    ],
    highlighted: true,
    cta: 'Get a Quote',
    badge: 'Most Popular',
    // pricePrefix: '₹',
    // priceNote: 'starts at · exact quote after scoping call',
  },
  {
    id: 'scale',
    name: 'Scale',
    price: { monthly: 0, yearly: 0 },
    description: 'For enterprises needing ongoing partnership and custom architecture.',
    features: [
      'Unlimited project scope',
      'Custom architecture planning',
      'Security audits & compliance',
      'White-label solutions available',
      'Ongoing retainer or milestone-based',
      'SLA-backed 12-month support',
      '24/7 priority support',
      'Dedicated point of contact',
      'On-site or embedded collaboration',
    ],
    highlighted: false,
    cta: 'Contact Us',
    // priceNote: 'milestone or retainer-based · let\'s talk',
  },
];

export const FAQS: FAQ[] = [
  {
    id: 'faq-1',
    question: 'How long does a typical project take?',
    answer: 'Most MVPs ship in 8-14 weeks. Complex enterprise projects can take 4-6 months. We provide a detailed timeline during our discovery phase, and our agile process means you see working software every sprint.',
  },
  {
    id: 'faq-2',
    question: 'Do I own the source code?',
    answer: 'Yes, 100%. You own all the code, designs, and assets we create for you. We provide full access to the repository from day one and complete handoff documentation at the end of the project.',
  },
  {
    id: 'faq-3',
    question: 'What technologies do you use?',
    answer: 'We specialize in React, Next.js, React Native, Flutter, Node.js, Python, and Go — with cloud infrastructure on AWS, GCP, and Azure. We choose the best stack for your specific needs during our technical discovery phase.',
  },
  {
    id: 'faq-4',
    question: 'Can you work with my existing team?',
    answer: 'Absolutely. Our Enterprise plan embeds our engineers directly in your team. We integrate with your existing workflows, tools, and communication channels — Slack, Jira, GitHub, whatever you use.',
  },
  {
    id: 'faq-5',
    question: 'What happens after the project launches?',
    answer: 'Every plan includes post-launch support (30-90 days depending on tier). Beyond that, we offer ongoing retainer partnerships for maintenance, feature development, and scaling support.',
  },
  {
    id: 'faq-6',
    question: 'How do you handle changes in project scope?',
    answer: 'Scope changes are a natural part of building software. We use agile methodology with flexible sprints, so we can adapt to changing requirements. Major scope changes are discussed transparently with timeline and cost implications.',
  },
  {
    id: 'faq-7',
    question: 'Do you offer fixed-price or hourly billing?',
    answer: 'We offer both. Our plans provide predictable monthly pricing, but we also do fixed-price projects for well-defined scopes. During discovery, we help you choose the billing model that works best for your situation.',
  },
];
